lsst/sphgeom

include/lsst/sphgeom/LonLat.h, include/lsst/sphgeom/UnitVector3d.h
This patch makes explicit `sphgeom`'s conventions for converting between vector and angular representations of a point on a sphere. It only formalizes existing behavior, so no client code should break. The conventions are documented at the class level rather than the method level, as each class has multiple conversion methods.
=> DM-7987: Ambiguous conversion between spherical coordinates and unit vectors 

tests/test_Angle.py, tests/test_AngleIntervals.py, tests/test_Box.py, tests/test_Box3d.py, tests/test_Chunker.py, tests/test_Circle.py, tests/test_ConvexPolygon.py, tests/test_Ellipse.py, tests/test_HtmPixelization.py, tests/test_Interval1d.py, tests/test_LonLat.py, tests/test_Matrix3d.py, tests/test_Mq3cPixelization.py, tests/test_NormalizedAngle.py, tests/test_Q3cPixelization.py, tests/test_RangeSet.py, tests/test_UnitVector3d.py, tests/test_Vector3d.py
Changes required for the [RFC-215/RFC-229 test file renaming](https://confluence.lsstcorp.org/pages/viewpage.action?pageId=58950873). See the top of that page for the exact changes required.
=> DM-11585: Add pytest support to packages

.github/workflows/build.yaml, .gitignore, MANIFEST.in, pyproject.toml, requirements.txt, setup.cfg, setup.py
This PR makes sphgeom pip installable by downstream packages without requiring a requirements.txt file to pre-populate the environment. The solution here relies on the pyproject.toml file to ensure that build dependencies are installed before setuptools is called to build and install the package. This relies on the new-ish PEP 517 mechanism for specifying the build requirements.
This work also removes the extra `setuptools_cpp` dependency as it didn't seem to add any value compared to pybind11's built-in setuptools integration.
=> DM-27354: Enable pip installation using pyproject.toml / PEP 517

include/lsst/sphgeom/codec.h
There was a broken code path for non-x86-64 architectures, so I fixed that and also added arm64 to the fast path.
=> Support Arm64

.github/workflows/cmake.yaml, CMakeLists.txt, include/lsst/sphgeom/NormalizedAngle.h, include/lsst/sphgeom/UnitVector3d.h, python/lsst/sphgeom/CMakeLists.txt, python/lsst/sphgeom/version.cmake, src/CMakeLists.txt, tests/CMakeLists.txt
Adds ability to build package with CMake in addition to eupspkg (allows to be included as submodule in other CMake projects, e.g. Qserv.)
=> DM-23308: Add CMake support

ups/sphgeom.cfg
This PR stops C++ imports of `sconsUtils`, fixing a missing tagfile error; `sconsUtils` is pure Python and does not produce Doxygen tag files.
=> DM-12659: Clean up Doxygen tagfile imports

.github/workflows/build.yaml, python/lsst/sphgeom/__init__.py, python/lsst/sphgeom/_healpixPixelization.py, python/lsst/sphgeom/_yaml.py, python/lsst/sphgeom/pixelization_abc.py, setup.cfg, tests/test_HealpixPixelization.py
Necessary for accessing Healpix-enabled butler registries with v23.
=> Backport DM-32605 and DM-32254

.github/workflows/cmake.yaml, pyproject.toml, python/lsst/sphgeom/_healpixPixelization.py, tests/test_HealpixPixelization.py
=> DM-35587: Change HEALPix backend from healpy to hpgeom

.github/workflows/build.yaml, .github/workflows/cmake.yaml, pyproject.toml
=> DM-35894: numpy.distutils requires pinning setuptools<65

include/lsst/sphgeom/codec.h
- Fixed the typo in decodeU64, which results in compilation error when compiled with aarch64-conda-linux-gnu-cc
- Modified `OPTIMIZED_LITTLE_ENDIAN` to support aarch64-conda-linux-gnu-cc compiler.
=> Fixed decodeU64 bug; added support for aarch64-conda-linux-gnu-cc

.github/workflows/build.yaml, .github/workflows/cmake.yaml, .github/workflows/lint.yaml, misc/makeHilbertLuts.py, pyproject.toml, python/lsst/sphgeom/_yaml.py, tests/test_Angle.py, tests/test_AngleIntervals.py, tests/test_Box.py, tests/test_Box3d.py, tests/test_Chunker.py, tests/test_Circle.py, tests/test_CompoundRegion.py, tests/test_ConvexPolygon.py, tests/test_Ellipse.py, tests/test_HealpixPixelization.py, tests/test_HtmPixelization.py, tests/test_Interval1d.py, tests/test_LonLat.py, tests/test_Matrix3d.py, tests/test_Mq3cPixelization.py, tests/test_NormalizedAngle.py, tests/test_Q3cPixelization.py, tests/test_RangeSet.py, tests/test_UnitVector3d.py, tests/test_Vector3d.py
=> DM-39857: Remove --flake8 option and add ruff config

.github/workflows/build.yaml
GitHub dropped macOS-10.15 long ago (probably in March when the PyPI uploads failed).
=> DM-39897: Use macos-11 for PyPI wheel build

.github/workflows/build.yaml, .github/workflows/rebase_checker.yaml, pyproject.toml, setup.py
=> DM-41805: Fix python 3.12 build

.github/workflows/build.yaml, .github/workflows/cmake.yaml, .github/workflows/lint.yaml, misc/makeHilbertLuts.py, pyproject.toml
=> Fix ruff failure

.github/workflows/build.yaml, pyproject.toml
=> DM-44487: Fix sphgeom PyPi upload

.github/workflows/build.yaml
=> DM-42695: Only upload weekly tag to PyPi when code changed

.github/workflows/build.yaml, tests/test_RangeSet.py
=> DM-46172: Enable linux_aarch64

include/lsst/sphgeom/CompoundRegion.h, include/lsst/sphgeom/Region.h, python/lsst/sphgeom/_region.cc, src/PixelFinder.h, src/Region.cc, tests/test_CompoundRegion.py, tests/test_HtmPixelization.py
=> DM-46239:  Add pixelization envelopes for Intersection/UnionRegion

.github/workflows/build.yaml
=> Turn off 3.8 and 3.9 in wheel build

python/lsst/sphgeom/_healpixPixelization.py, tests/test_HealpixPixelization.py
This PR fixes `ValueError: Radius must be positive` for a case when Circle region with zero-radius is used to represent a point.
=> DM-50218: Fixed an error when computing envelope for point region

CMakeLists.txt, python/lsst/sphgeom/CMakeLists.txt
Newer installations are starting to whinge about soon-to-be-deprecated `cmake` < 3.10.  This upgrades minimal version from 3.1 to 3.10, and also updates to modern find python usage for pybind11.
=> DM-51974: Update to `cmake` 3.12 or later
